export type DefenseSourceCategory = 'journalism' | 'official' | 'analysis'

export interface DefenseFeedSource {
  id: string
  name: string
  category: DefenseSourceCategory
  sourceBadge: string
  feedUrl: string
  homepageUrl: string
  weight: number
}

export const defenseFeedSources: DefenseFeedSource[] = [
  {
    id: 'breaking-defense',
    name: 'Breaking Defense',
    category: 'journalism',
    sourceBadge: 'Analysis',
    feedUrl: 'https://breakingdefense.com/feed/',
    homepageUrl: 'https://breakingdefense.com/',
    weight: 5,
  },
  {
    id: 'defense-news',
    name: 'Defense News',
    category: 'journalism',
    sourceBadge: 'Analysis',
    feedUrl: 'https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml',
    homepageUrl: 'https://www.defensenews.com/',
    weight: 5,
  },
  {
    id: 'c4isrnet',
    name: 'C4ISRNET',
    category: 'journalism',
    sourceBadge: 'Analysis',
    feedUrl: 'https://www.c4isrnet.com/arc/outboundfeeds/rss/?outputType=xml',
    homepageUrl: 'https://www.c4isrnet.com/',
    weight: 4,
  },
  {
    id: 'defense-one',
    name: 'Defense One',
    category: 'journalism',
    sourceBadge: 'Analysis',
    feedUrl: 'https://www.defenseone.com/rss/all/',
    homepageUrl: 'https://www.defenseone.com/',
    weight: 4,
  },
  {
    id: 'the-war-zone',
    name: 'The War Zone',
    category: 'journalism',
    sourceBadge: 'Analysis',
    feedUrl: 'https://www.twz.com/feed',
    homepageUrl: 'https://www.twz.com/',
    weight: 4,
  },
  {
    id: 'defense-scoop',
    name: 'DefenseScoop',
    category: 'journalism',
    sourceBadge: 'Analysis',
    feedUrl: 'https://defensescoop.com/feed/',
    homepageUrl: 'https://defensescoop.com/',
    weight: 4,
  },
  {
    id: 'usni-news',
    name: 'USNI News',
    category: 'journalism',
    sourceBadge: 'Analysis',
    feedUrl: 'https://news.usni.org/feed',
    homepageUrl: 'https://news.usni.org/',
    weight: 4,
  },
  {
    id: 'naval-news',
    name: 'Naval News',
    category: 'journalism',
    sourceBadge: 'Analysis',
    feedUrl: 'https://www.navalnews.com/feed/',
    homepageUrl: 'https://www.navalnews.com/',
    weight: 3,
  },
  {
    id: 'war-on-the-rocks',
    name: 'War on the Rocks',
    category: 'analysis',
    sourceBadge: 'Analysis',
    feedUrl: 'https://warontherocks.com/feed/',
    homepageUrl: 'https://warontherocks.com/',
    weight: 4,
  },
  {
    id: 'real-clear-defense',
    name: 'RealClearDefense',
    category: 'analysis',
    sourceBadge: 'Analysis',
    feedUrl: 'https://www.realcleardefense.com/index.xml',
    homepageUrl: 'https://www.realcleardefense.com/',
    weight: 2,
  },
  {
    id: 'csis',
    name: 'CSIS',
    category: 'analysis',
    sourceBadge: 'Analysis',
    feedUrl: 'https://www.csis.org/rss.xml',
    homepageUrl: 'https://www.csis.org/',
    weight: 3,
  },
  {
    id: 'dod-news',
    name: 'U.S. Department of Defense News',
    category: 'official',
    sourceBadge: 'DoD release',
    feedUrl: 'https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=945&max=25',
    homepageUrl: 'https://www.defense.gov/News/',
    weight: 5,
  },
  {
    id: 'dod-releases',
    name: 'U.S. Department of Defense Releases',
    category: 'official',
    sourceBadge: 'DoD release',
    feedUrl: 'https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=400&Site=945&max=25',
    homepageUrl: 'https://www.defense.gov/News/Releases/',
    weight: 5,
  },
  {
    id: 'us-air-force',
    name: 'U.S. Air Force',
    category: 'official',
    sourceBadge: 'DoD release',
    feedUrl: 'https://www.af.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1&max=25',
    homepageUrl: 'https://www.af.mil/News/',
    weight: 3,
  },
  {
    id: 'us-marines',
    name: 'U.S. Marine Corps',
    category: 'official',
    sourceBadge: 'DoD release',
    feedUrl: 'https://www.marines.mil/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=1&max=25',
    homepageUrl: 'https://www.marines.mil/News/',
    weight: 3,
  },
  {
    id: 'uk-mod',
    name: 'UK Ministry of Defence',
    category: 'official',
    sourceBadge: 'Policy doc',
    feedUrl: 'https://www.gov.uk/government/organisations/ministry-of-defence.atom',
    homepageUrl: 'https://www.gov.uk/government/organisations/ministry-of-defence',
    weight: 3,
  },
]
