export const storyDigestSchema = {
  name: 'storyDigest',
  type: 'document',
  title: 'Story Digest',
  fields: [
    {name: 'clusterKey', type: 'string'},
    {name: 'representativeArticleId', type: 'string'},
    {name: 'topicLabel', type: 'string'},
    {name: 'headline', type: 'string'},
    {name: 'dek', type: 'text'},
    {name: 'keyPoints', type: 'array', of: [{type: 'string'}]},
    {name: 'whyItMatters', type: 'text'},
    {name: 'riskLevel', type: 'string'},
    {
      name: 'citations',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {name: 'articleId', type: 'string'},
            {name: 'headline', type: 'string'},
            {name: 'sourceName', type: 'string'},
            {name: 'url', type: 'url'},
            {name: 'sourceRole', type: 'string'},
          ],
        },
      ],
    },
    {name: 'citationCount', type: 'number'},
    {name: 'hasOfficialSource', type: 'boolean'},
    {name: 'reportingCount', type: 'number'},
    {name: 'analysisCount', type: 'number'},
    {name: 'officialCount', type: 'number'},
    {name: 'opinionCount', type: 'number'},
    {name: 'pressReleaseDriven', type: 'boolean'},
    {name: 'opinionLimited', type: 'boolean'},
    {name: 'sourceDiversity', type: 'number'},
    {name: 'generationMode', type: 'string'},
    {name: 'transformStatus', type: 'string'},
    {name: 'reviewStatus', type: 'string'},
    {name: 'isCongestedCluster', type: 'boolean'},
    {name: 'articleCount24h', type: 'number'},
    {name: 'uniqueSources24h', type: 'number'},
    {name: 'congestionScore', type: 'number'},
    {name: 'generatedAt', type: 'datetime'},
  ],
}
